apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: entsoe-price-fetcher
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: electricity-pricing

images:
  - name: entsoe-price-fetcher
    newTag: latest
